module vsphere {
  source              = "./modules/vsphere"
  cluster             = var.cluster
  controlplane        = var.controlplane
  datacenter          = var.datacenter
  datastore           = var.datastore
  dns_servers         = var.dns_servers
  etcd                = var.etcd
  gateway_address     = var.gateway_address
  latency_sensitivity = var.latency_sensitivity
  network             = var.network
  resource_naming     = var.resource_naming
  resource_pool       = var.resource_pool
  search_domains      = var.search_domains
  template            = var.template
  vm_folder           = var.vm_folder
  vm_user             = var.vm_user
  worker_groups       = var.worker_groups
}
